#!/bin/bash

# reset server wwwroot
rm -rf ./Server/wwwroot/*
rmdir ./Server/wwwroot/
mkdir ./Server/wwwroot/

# publish and copy over published contents to server
cd ./Client/
/usr/bin/dotnet publish -o output
cp -r ./output/wwwroot/* ../Server/wwwroot/
rm -rf ./output/*
rmdir ./output/

# copy shared models over to server
cd ../Server/
cp -rf ../Shared/Models/* ./Models/


